[2022-03-14 05:05:24,995] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-14T05:05:23.862143+00:00 [queued]>
[2022-03-14 05:05:25,010] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-14T05:05:23.862143+00:00 [queued]>
[2022-03-14 05:05:25,011] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 05:05:25,012] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 05:05:25,013] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 05:05:25,028] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-03-14 05:05:23.862143+00:00
[2022-03-14 05:05:25,034] {standard_task_runner.py:52} INFO - Started process 797 to run task
[2022-03-14 05:05:25,038] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-03-14T05:05:23.862143+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmpgw_g5siq', '--error-file', '/tmp/tmpww4enheu']
[2022-03-14 05:05:25,040] {standard_task_runner.py:77} INFO - Job 12: Subtask load_seed_data_once
[2022-03-14 05:05:25,122] {logging_mixin.py:109} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-03-14T05:05:23.862143+00:00 [running]> on host efa886db3485
[2022-03-14 05:05:25,270] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T05:05:23.862143+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T05:05:23.862143+00:00
[2022-03-14 05:05:25,273] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-14 05:05:25,276] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-03-14 05:05:25,303] {subprocess.py:85} INFO - Output:
[2022-03-14 05:05:28,421] {subprocess.py:89} INFO - Running with dbt=0.20.0
[2022-03-14 05:05:32,710] {subprocess.py:89} INFO - Found 5 models, 0 tests, 0 snapshots, 0 analyses, 338 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-03-14 05:05:32,713] {subprocess.py:89} INFO - 
[2022-03-14 05:05:35,298] {subprocess.py:89} INFO - 05:05:35 | Concurrency: 200 threads (target='dev')
[2022-03-14 05:05:35,300] {subprocess.py:89} INFO - 05:05:35 |
[2022-03-14 05:05:35,362] {subprocess.py:89} INFO - 05:05:35 | 1 of 3 START seed file public.bookings_1............................. [RUN]
[2022-03-14 05:05:35,363] {subprocess.py:89} INFO - 05:05:35 | 2 of 3 START seed file public.bookings_2............................. [RUN]
[2022-03-14 05:05:35,364] {subprocess.py:89} INFO - 05:05:35 | 3 of 3 START seed file public.customers.............................. [RUN]
[2022-03-14 05:05:36,263] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-14 05:05:36,264] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-14 05:05:36,265] {subprocess.py:89} INFO - release.
[2022-03-14 05:05:36,266] {subprocess.py:89} INFO - 
[2022-03-14 05:05:36,266] {subprocess.py:89} INFO - For more information, see:
[2022-03-14 05:05:36,267] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-14 05:05:36,268] {subprocess.py:89} INFO - * Deprecation Warning: The quote_columns parameter was not set for seeds, so the
[2022-03-14 05:05:36,268] {subprocess.py:89} INFO - default value of False was chosen. The default will change to True in a future
[2022-03-14 05:05:36,269] {subprocess.py:89} INFO - release.
[2022-03-14 05:05:36,270] {subprocess.py:89} INFO - 
[2022-03-14 05:05:36,271] {subprocess.py:89} INFO - For more information, see:
[2022-03-14 05:05:36,272] {subprocess.py:89} INFO - https://docs.getdbt.com/v0.15/docs/seeds#section-specify-column-quoting
[2022-03-14 05:05:37,778] {subprocess.py:89} INFO - 05:05:37 | 1 of 3 OK loaded seed file public.bookings_1......................... [[32mINSERT 7[0m in 2.41s]
[2022-03-14 05:05:37,904] {subprocess.py:89} INFO - 05:05:37 | 3 of 3 OK loaded seed file public.customers.......................... [[32mINSERT 2[0m in 2.54s]
[2022-03-14 05:05:37,954] {subprocess.py:89} INFO - 05:05:37 | 2 of 3 OK loaded seed file public.bookings_2......................... [[32mINSERT 7[0m in 2.59s]
[2022-03-14 05:05:38,578] {subprocess.py:89} INFO - 05:05:38 |
[2022-03-14 05:05:38,579] {subprocess.py:89} INFO - 05:05:38 | Finished running 3 seeds in 5.86s.
[2022-03-14 05:05:38,610] {subprocess.py:89} INFO - 
[2022-03-14 05:05:38,613] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-03-14 05:05:38,615] {subprocess.py:89} INFO - 
[2022-03-14 05:05:38,616] {subprocess.py:89} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-03-14 05:05:39,857] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-14 05:05:39,888] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220314T050523, start_date=20220314T050524, end_date=20220314T050539
[2022-03-14 05:05:39,913] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 05:05:39,951] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
