[2022-03-16 03:04:33,016] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform manual__2022-03-16T03:04:32.584772+00:00 [queued]>
[2022-03-16 03:04:33,027] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform manual__2022-03-16T03:04:32.584772+00:00 [queued]>
[2022-03-16 03:04:33,027] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 03:04:33,028] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-16 03:04:33,029] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 03:04:33,041] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): daily_transform> on 2022-03-16 03:04:32.584772+00:00
[2022-03-16 03:04:33,046] {standard_task_runner.py:52} INFO - Started process 1759 to run task
[2022-03-16 03:04:33,051] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '2_daily_transformation_analysis', 'daily_transform', 'manual__2022-03-16T03:04:32.584772+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/transform_and_analysis.py', '--cfg-path', '/tmp/tmpqbo13x7e', '--error-file', '/tmp/tmpjte05fae']
[2022-03-16 03:04:33,052] {standard_task_runner.py:77} INFO - Job 51: Subtask daily_transform
[2022-03-16 03:04:33,115] {logging_mixin.py:109} INFO - Running <TaskInstance: 2_daily_transformation_analysis.daily_transform manual__2022-03-16T03:04:32.584772+00:00 [running]> on host b1edfeccb8dc
[2022-03-16 03:04:33,211] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_daily_transformation_analysis
AIRFLOW_CTX_TASK_ID=daily_transform
AIRFLOW_CTX_EXECUTION_DATE=2022-03-16T03:04:32.584772+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-16T03:04:32.584772+00:00
[2022-03-16 03:04:33,212] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-16 03:04:33,213] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt run --models transform --profiles-dir .']
[2022-03-16 03:04:33,225] {subprocess.py:85} INFO - Output:
[2022-03-16 03:04:36,786] {subprocess.py:89} INFO - 03:04:36  Running with dbt=1.0.0
[2022-03-16 03:04:36,890] {subprocess.py:89} INFO - 03:04:36  Unable to do partial parsing because of a dbt version mismatch. Saved manifest version: 1.0.3. Current version: 1.0.0.
[2022-03-16 03:04:39,554] {subprocess.py:89} INFO - 03:04:39  [WARNING]: 'customers' is a seed node, but it is specified in the models section of
[2022-03-16 03:04:39,555] {subprocess.py:89} INFO - models/transform/schema_transform.yml. To fix this error, place the `customers`
[2022-03-16 03:04:39,555] {subprocess.py:89} INFO - specification under the seeds key instead.
[2022-03-16 03:04:39,639] {subprocess.py:89} INFO - 03:04:39  Found 5 models, 2 tests, 0 snapshots, 0 analyses, 581 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
[2022-03-16 03:04:39,642] {subprocess.py:89} INFO - 03:04:39
[2022-03-16 03:04:41,258] {subprocess.py:89} INFO - 03:04:41  Concurrency: 200 threads (target='dev')
[2022-03-16 03:04:41,260] {subprocess.py:89} INFO - 03:04:41
[2022-03-16 03:04:41,308] {subprocess.py:89} INFO - 03:04:41  1 of 3 START view model transform.combined_bookings............................. [RUN]
[2022-03-16 03:04:41,310] {subprocess.py:89} INFO - 03:04:41  2 of 3 START view model transform.customer...................................... [RUN]
[2022-03-16 03:04:42,090] {subprocess.py:89} INFO - 03:04:42  2 of 3 OK created view model transform.customer................................. [SUCCESS 1 in 0.78s]
[2022-03-16 03:04:42,336] {subprocess.py:89} INFO - 03:04:42  1 of 3 OK created view model transform.combined_bookings........................ [SUCCESS 1 in 1.02s]
[2022-03-16 03:04:42,341] {subprocess.py:89} INFO - 03:04:42  3 of 3 START view model transform.prepped_data.................................. [RUN]
[2022-03-16 03:04:43,118] {subprocess.py:89} INFO - 03:04:43  3 of 3 OK created view model transform.prepped_data............................. [SUCCESS 1 in 0.77s]
[2022-03-16 03:04:43,148] {subprocess.py:89} INFO - 03:04:43
[2022-03-16 03:04:43,152] {subprocess.py:89} INFO - 03:04:43  Finished running 3 view models in 3.50s.
[2022-03-16 03:04:43,180] {subprocess.py:89} INFO - 03:04:43
[2022-03-16 03:04:43,181] {subprocess.py:89} INFO - 03:04:43  Completed successfully
[2022-03-16 03:04:43,183] {subprocess.py:89} INFO - 03:04:43
[2022-03-16 03:04:43,184] {subprocess.py:89} INFO - 03:04:43  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-03-16 03:04:44,415] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-16 03:04:44,443] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=2_daily_transformation_analysis, task_id=daily_transform, execution_date=20220316T030432, start_date=20220316T030433, end_date=20220316T030444
[2022-03-16 03:04:44,483] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-16 03:04:44,519] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
