[2022-03-14 05:07:33,987] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_analysis manual__2022-03-14T05:07:19.116572+00:00 [queued]>
[2022-03-14 05:07:34,001] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_analysis manual__2022-03-14T05:07:19.116572+00:00 [queued]>
[2022-03-14 05:07:34,002] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 05:07:34,003] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-14 05:07:34,004] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-14 05:07:34,017] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): daily_analysis> on 2022-03-14 05:07:19.116572+00:00
[2022-03-14 05:07:34,025] {standard_task_runner.py:52} INFO - Started process 1338 to run task
[2022-03-14 05:07:34,039] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '2_daily_transformation_analysis', 'daily_analysis', 'manual__2022-03-14T05:07:19.116572+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/transform_and_analysis.py', '--cfg-path', '/tmp/tmp7ze_whz7', '--error-file', '/tmp/tmpz6jrsbf3']
[2022-03-14 05:07:34,041] {standard_task_runner.py:77} INFO - Job 14: Subtask daily_analysis
[2022-03-14 05:07:34,144] {logging_mixin.py:109} INFO - Running <TaskInstance: 2_daily_transformation_analysis.daily_analysis manual__2022-03-14T05:07:19.116572+00:00 [running]> on host efa886db3485
[2022-03-14 05:07:34,247] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_daily_transformation_analysis
AIRFLOW_CTX_TASK_ID=daily_analysis
AIRFLOW_CTX_EXECUTION_DATE=2022-03-14T05:07:19.116572+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-14T05:07:19.116572+00:00
[2022-03-14 05:07:34,249] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-14 05:07:34,250] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt run --models analysis --profiles-dir .']
[2022-03-14 05:07:34,260] {subprocess.py:85} INFO - Output:
[2022-03-14 05:07:36,699] {subprocess.py:89} INFO - Running with dbt=0.20.0
[2022-03-14 05:07:39,500] {subprocess.py:89} INFO - Found 5 models, 0 tests, 0 snapshots, 0 analyses, 338 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-03-14 05:07:39,503] {subprocess.py:89} INFO - 
[2022-03-14 05:07:41,608] {subprocess.py:89} INFO - 05:07:41 | Concurrency: 200 threads (target='dev')
[2022-03-14 05:07:41,609] {subprocess.py:89} INFO - 05:07:41 |
[2022-03-14 05:07:41,660] {subprocess.py:89} INFO - 05:07:41 | 1 of 2 START view model analysis.hotel_count_by_day.................. [RUN]
[2022-03-14 05:07:41,662] {subprocess.py:89} INFO - 05:07:41 | 2 of 2 START view model analysis.thirty_day_avg_cost................. [RUN]
[2022-03-14 05:07:42,923] {subprocess.py:89} INFO - 05:07:42 | 1 of 2 OK created view model analysis.hotel_count_by_day............. [[32mSUCCESS 1[0m in 1.26s]
[2022-03-14 05:07:42,979] {subprocess.py:89} INFO - 05:07:42 | 2 of 2 OK created view model analysis.thirty_day_avg_cost............ [[32mSUCCESS 1[0m in 1.31s]
[2022-03-14 05:07:43,616] {subprocess.py:89} INFO - 05:07:43 |
[2022-03-14 05:07:43,618] {subprocess.py:89} INFO - 05:07:43 | Finished running 2 view models in 4.11s.
[2022-03-14 05:07:43,643] {subprocess.py:89} INFO - 
[2022-03-14 05:07:43,644] {subprocess.py:89} INFO - [32mCompleted successfully[0m
[2022-03-14 05:07:43,646] {subprocess.py:89} INFO - 
[2022-03-14 05:07:43,647] {subprocess.py:89} INFO - Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2022-03-14 05:07:44,905] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-14 05:07:44,936] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=2_daily_transformation_analysis, task_id=daily_analysis, execution_date=20220314T050719, start_date=20220314T050733, end_date=20220314T050744
[2022-03-14 05:07:44,988] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-14 05:07:45,021] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
